### ISSUE TITLE
Classes Faltando

### ISSUE THREAD

**Issue by AngeloBestetti** [alexandresanlim/pix-dynamic-payload-generator.net#1]
Estou realizando alguns teste e esta classe Merchant e a Classe DynamicPayload e Payload nao existem na solucao.

https://github.com/alexandresanlim/pix-dynamic-payload-generator.net/blob/33b723a486c50afbdbf6f45a58687ce2e02f0da4/pix-dynamic-payload-generator.net-test/QrCodeTest.cs#L27

**Comment by alexandresanlim** [comment]
Angelo, elas fazem parte deste outro projeto: https://github.com/alexandresanlim/pix-payload-generator.net

**Comment by AngeloBestetti** [comment]
Ok muito obrigado

Em qua., 28 de abr. de 2021 14:35, Alexandre Sanlim <
***@***.***> escreveu:
