### ISSUE TITLE
Certificado digital x509

### ISSUE THREAD

**Issue by paulopereira-tec** [alexandresanlim/pix-dynamic-payload-generator.net#11]
Na seção "como iniciar" está descrevendo o uso de um certificado x509. 

 new StartConfig(
       _baseUrl: "https://api-pix-h.seupsp.com.br",
       _clientId: "client-id-fornecido-pelo-psp",
       _clientSecret: "client-secret-fornecido-pelo-psp",
      _certificate: new System.Security.Cryptography.X509Certificates.X509Certificate2(@".\certificado.p12")
       );

Não sei se o local para perguntar seria esse. Se não for, peço desculpas.

Posso usar qualquer certificado digital? Ex. e-CNPJ?

**Comment by alexandresanlim** [comment]
Não, este certificado é fornecido pelo PSP e exclusivo para o uso do Pix, cada empresa tem uma forma de fornece-lo, é preciso ler a documentação da qual está implementando para saber como conseguir.
