### ISSUE TITLE
Onde inicilaizar  new StartConfig(...)

### ISSUE THREAD

**Issue by premy** [alexandresanlim/pix-dynamic-payload-generator.net#2]
Oi Alexandre, obrigado pelo esforço, mas tenho dúvidas de onde inicializar  `new StartConfig(...)`.

**Comment by alexandresanlim** [comment]
Opa @premy , em qualquer método onde sua aplicação é iniciada.

**Comment by premy** [comment]
No caso coloquei no global.asax application_startup, certo?
