### ISSUE TITLE
Erro: não são permitidos propriedades adicionais 

### ISSUE THREAD

**Issue by premy** [alexandresanlim/pix-dynamic-payload-generator.net#3]
Tem ideia o que pode causar este erro:

`{"nome":"json_invalido","mensagem":"Valores ou tipos de campo inválidos","erros":[{"chave":"additionalProperties","caminho":".body.calendario","mensagem":"não são permitidas propriedades adicionais"}]}`

Usei `var cob = new CobRequest(_chave: "1b0e2743-0769-4f21-b0b7-9cfddb2a5a2b")` tal qual está no wiki 4 QR Code dinâmico, como gerar?

meu psp é gerencianet e estou testando em homologação. Pesquisei no discord da gerencianet, mas não encontrei nenhuma luz sobre isto.

**Comment by alexandresanlim** [comment]
O valor da propriedade "_chave" deve ser a chave que pix que você tem cadastrado no seu PSP. Foi atribuído um valor para a propriedade "Calendario" dentro do CobRquest? Se sim, poderia colocar aqui qual foi o valor atribuído?

**Comment by premy** [comment]
Deve ser problema da chave então, pois ainda não cadastrei, pensando que em homologação poderia ser uma chave fake. Logo mais vou tentar com uma chave válida.
o cobRequest é idêntico ao que está na wiki, então Calendário é:
`Calendario = new Calendario
    {
        Expiracao = 3600
    },`
Falarei depois como foi com chave válida, obrigado pela sua ajuda.

**Comment by premy** [comment]
Desculpe a demora, mas tentei com chave válida e continua o mesmo erro.

**Comment by henriquefelipe** [comment]
Também estou com esse mesmo problema, conseguiu resolver @premy ?

**Comment by alexandresanlim** [comment]
Boa tarde, bug resolvido na ultima versão [1.0.24](https://www.nuget.org/packages/pix-dynamic-payload-generator.net/1.0.24)
