### ISSUE TITLE
Erro Token Create - 'Unsupported Media Type' 

### ISSUE THREAD

**Issue by rubgithub** [alexandresanlim/pix-dynamic-payload-generator.net#5]
Estou homologando no BB e ao gerar o token é retornado o erro:
> StatusCode: 415, ReasonPhrase: 'Unsupported Media Type'

Tente contornar de várias formas mas a solução foi substiruir

```
//var content = "{\r\n    \"grant_type\": \"client_credentials\"\r\n}";
//requestMessage.Content = new StringContent(content, Encoding.UTF8, "application/json");
```

Por

```
 requestMessage.Content = new FormUrlEncodedContent(new[]
 {
     new KeyValuePair<string, string>("grant_type", "client_credentials")
});
```

**Comment by alexandresanlim** [comment]
Opa! A geração do token e certificado é diferente para cada PSP,  nosso pacote é util somente após a geração, talvez você consiga um suporte melhor, como os responsáveis do BB.

Um outro ponto é que o BB não segue o padrão oficial da API Pix, você pode acompanhar as empresas que estão seguindo aqui: https://github.com/alexandresanlim/pix-dynamic-payload-generator.net/wiki/2-QR-Code-din%C3%A2mico,-PSPs-compat%C3%ADveis, desta forma você também não conseguiria integrar como este pacote por esse motivo.
