### ISSUE TITLE
Erro ao gerar para o Sicredi

### ISSUE THREAD

**Issue by dionathanbatista** [alexandresanlim/pix-dynamic-payload-generator.net#7]
Estou fazendo testes para o Sicredi, porem esta com erro quando utilizo o certificado.cer que foi gerado:

![ErroApiPixSicredi01](https://github.com/alexandresanlim/pix-dynamic-payload-generator.net/assets/19978403/75d01735-6d45-4a13-9add-dca99797ab52)
Tentei converter o certificado em .p12 mas da esse erro:
![ErroApiPixSicredi02](https://github.com/alexandresanlim/pix-dynamic-payload-generator.net/assets/19978403/ea8e3911-9f44-4847-93ab-8f26882e7d7f)
Alguem poderia me dar uma luz?
estou usando url psp https://api-pix-h.sicredi.com.br para testar

**Comment by alexandresanlim** [comment]
Pelo que aparenta é algum problema relacionado a premissões do seu certificado, acredito que você deveria buscar o suporte da Sicred para entender melhor o problema.

**Comment by dionathanbatista** [comment]
Olá Bom dia,
Encaminhei um email ao suporte deles, vou aguardar um retorno
Obrigado
